spring:
  application:
    name: api-gateway

  # API gateway config
  cloud:
    gateway:
      routes:
        - id: order-svc
          uri: lb://ORDER-SVC
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
        - id: inventory-svc
          uri: lb://INVENTORY-SVC  # Corrected URI format
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
