spring.application.name=notification-svc
server.port = 9070

spring.kafka.consumer.group-id=notification-svc

#MySQL configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/notification-svc
spring.datasource.password=Prudhviraj@852
spring.datasource.username=root


#Kafka configuration
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#Note: When we run the project, the console will display messages in a loop due to trust issues. To resolve this, we need to add the following property:
spring.kafka.consumer.properties.spring.json.trusted.packages=com.prudhviraj.ecommerce.kafka.*


#Note
# We need to create the same package name in the consumer as the producer package name to ensure that the event classes can be properly serialized and deserialized. For example:
#   - **Producer Package Name:** `com.prudhviraj.ecommerce.kafka.user_svc.events`
#   - **Consumer Package Name:** `com.prudhviraj.ecommerce.kafka.user_svc.events`
# This consistency in package structure allows the consumer to locate and process the events produced by the producer without encountering trust issues or serialization errors.

