spring.application.name=user-svc
server.port = 9050
#MySQL configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/user-svc
spring.datasource.password=Prudhviraj@852
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

kafka.topic.user-topic=user-topic
kafka.topic.user-created-topic=user-created-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer








